[versions]
activity-compose = "1.12.4"
android-gradle-plugin = "8.13.2"
android-material = "1.13.0"
androidx-test-ext-junit = "1.3.0"
appcompat = "1.7.1"
arrow = "2.2.1.1"
coil-bom = "3.3.0"
compose-bom = "2026.01.01"
compose-material3 = "1.5.0-alpha14"
core-ktx = "1.17.0"
core-splashscreen = "1.2.0"
coroutines = "1.10.2"
crashlytics = "3.0.6"
datastore = "1.2.0"
espresso-core = "3.7.0"
firebase-bom = "34.9.0"
google-gms-google-services = "4.4.4"
junit = "4.13.2"
koin = "4.2.0-RC1"
kotlin = "2.3.10"
kotlinx-collections-immutable = "0.4.0"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
ksp = "2.3.5"
ktor = "3.4.0"
lifecycle = "2.10.0"
nav3Core = "1.1.0-alpha04"
lifecycleViewmodelNav3 = "2.10.0"
room = "2.8.4"
spotless-plugin-gradle = "8.2.1"
sonarqube = "7.2.2.6593"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidX-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# Android
androidX-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidX-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
androidX-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

# Lifecycle
androidX-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidX-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

# Compose
androidX-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidX-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidX-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidX-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidX-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidX-compose-uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidX-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidX-compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidX-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
androidX-compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidX-compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Navigation 3
androidX-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidX-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidX-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }

# Room
androidX-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidX-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidX-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidX-room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# Datastore
androidX-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Coroutines
kotlinX-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinX-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-navigation3 = { group = "io.insert-koin", name = "koin-compose-navigation3" }

# Ktor
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding" }

# Kotlin std
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-metadata-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlin" }

# KotlinX
kotlinX-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinX-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinX-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

# Coil
coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil-bom" }
coil = { group = "io.coil-kt.coil3", name = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg" }
coil-test = { group = "io.coil-kt.coil3", name = "coil-test" }

# Arrow
arrow-bom = { group = "io.arrow-kt", name = "arrow-stack", version.ref = "arrow" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines" }

# Spotless for BuildSrc convention script
spotless-plugin-gradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless-plugin-gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-gms-google-services" }
google-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinX-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinX-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
