[versions]
activity-compose = "1.12.1"
android-gradle-plugin = "8.13.1"
androidx-hilt = "1.3.0"
androidx-test-ext-junit = "1.3.0"
appcompat = "1.7.1"
coil-bom = "3.3.0"
compose-bom = "2025.11.01"
core-ktx = "1.17.0"
coroutines = "1.10.2"
dagger = "2.57.2"
espresso-core = "3.7.0"
google-gms-google-services = "4.4.4"
junit = "4.13.2"
kotlin = "2.2.21"
lifecycle = "2.10.0"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
room = "2.8.4"
spotless-plugin-gradle = "8.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidX-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# Android
androidX-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidX-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
androidX-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "34.6.0" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

# Lifecycle
androidX-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidX-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

# Compose
androidX-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidX-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidX-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidX-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidX-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidX-compose-uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidX-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidX-compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidX-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.5.0-alpha10" }
androidX-hilt-navigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
androidX-compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidX-compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Navigation 3
androidX-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidX-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidX-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }

# Room
androidX-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidX-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidX-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidX-room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# Datastore
androidX-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.2.0" }

# Coroutines
kotlinX-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinX-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Hilt
androidX-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
androidX-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidx-hilt" }

# Dagger
google-dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
google-dagger-hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
google-dagger-hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }

# Retrofit
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version = "5.3.2" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
retrofit-bom = { group = "com.squareup.retrofit2", name = "retrofit-bom", version = "3.0.0" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit" }
retrofit-converter-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization" }

# Kotlin std
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

# KotlinX
kotlinX-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
kotlinX-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.7.1-0.6.x-compat" }
kotlinX-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version = "0.4.0" }

# Coil
coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil-bom" }
coil = { group = "io.coil-kt.coil3", name = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg" }
coil-test = { group = "io.coil-kt.coil3", name = "coil-test" }

# Material kolor
material-kolor = { group = "com.materialkolor", name = "material-kolor", version = "5.0.0-alpha02" }

# Spotless for BuildSrc convention script
spotless-plugin-gradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless-plugin-gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
google-ksp = { id = "com.google.devtools.ksp", version = "2.3.3" }
google-daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-gms-google-services" }
google-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinX-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinX-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]

